#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

THIS_DIR=`cd $(dirname "$0"); echo -n $PWD`
source "$THIS_DIR/config"

echo "mandando a $VM_NAME parar"

case $OS_TYPE in
   RedHat) VBoxManage controlvm $VM_NAME poweroff;;
   Fedora*) VBoxManage controlvm $VM_NAME acpipowerbutton;;
   *) echo "Tipo \"$OS_TYPE\" não está configurado!"; exit 1;;
esac

echo -n "aguardando até a $VM_NAME parar ... "
while true; do VBoxManage list runningvms | grep -q $VM_NAME && sleep 1 || break; done
echo ok

echo "removendo o CD de instalação e inserindo o do VirtualBox Guest Additions"
VBoxManage storageattach $VM_NAME --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium additions

echo "reiniciando a $VM_NAME"
VBoxManage startvm $VM_NAME

cat <<'EOF'

Aguarde a VM ser iniciada ...
Logue-se como aluno (senha @alun0123) e execute os seguintes comandos:

configurar-vm-apos-instalacao
history -c

Volte para um shell na máquina HOST (a que está executando o VirtualBox) e execute:

./pos-install-2
EOF
